title: Yixin Chen
position: Ph.D. Candidate
affiliation: Boston University
email: chenyx0612 (at) gmail.com
email_address: chenyx0612@gmail.com
keywords: Yixin Chen
LinkedIn_link: www.linkedin.com/in/yixin-chen-cyx
github_link: https://github.com/yxyxchen
avatar: ./assets/img/profilePic.jpg
google_analytics: UA-31678746-1
favicon: ./assets/img/profilePic.jpg
favicon_dark: ./assets/img/profilePic.jpg
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://yxyxchen.github.io
remote_theme: yaoyao-liu/minimal-light
